version: '2.1'

services:

    fedora:
        image:
            "phymatopus/fedora:${buildtag}"
        labels:
            uk.ac.roe.phymatopus.buildtag: "${buildtag}"
        build:
            context: '../fedora'

    java:
        image:
            "phymatopus/java:${buildtag}"
        labels:
            uk.ac.roe.phymatopus.buildtag: "${buildtag}"
        build:
            context: '../java'
        depends_on:
            - fedora

    tomcat:
        image:
            "phymatopus/tomcat:${buildtag}"
        labels:
            uk.ac.roe.phymatopus.buildtag: "${buildtag}"
        build:
            context: '../tomcat'
        depends_on:
            - java

    builder:
        image:
           "phymatopus/builder:${buildtag}"
        build:
            context: '../builder'
        depends_on:
            - java

    zookeeper:
        image:
            "confluentinc/cp-zookeeper:3.2.0"

    kafka:
        image:
            "confluentinc/cp-kafka:3.2.0"


